---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	transcribe_recording(transcribe_recording)
	diarize_speakers(diarize_speakers)
	extract_tasks(extract_tasks)
	build_jira_tickets(build_jira_tickets)
	raise_ready_tickets(raise_ready_tickets)
	generate_summary(generate_summary)
	prepare_draft_review(prepare_draft_review)
	select_next_draft(select_next_draft)
	collect_review_decision(collect_review_decision)
	review_agent_edit(review_agent_edit)
	approve_draft(approve_draft)
	reject_draft(reject_draft)
	__end__([<p>__end__</p>]):::last
	__start__ --> transcribe_recording;
	approve_draft --> select_next_draft;
	build_jira_tickets --> raise_ready_tickets;
	collect_review_decision -.-> approve_draft;
	collect_review_decision -.-> reject_draft;
	collect_review_decision -.-> review_agent_edit;
	diarize_speakers --> extract_tasks;
	diarize_speakers --> generate_summary;
	extract_tasks --> build_jira_tickets;
	generate_summary --> prepare_draft_review;
	prepare_draft_review --> select_next_draft;
	raise_ready_tickets --> prepare_draft_review;
	reject_draft --> select_next_draft;
	review_agent_edit -.-> approve_draft;
	review_agent_edit -.-> collect_review_decision;
	select_next_draft -. &nbsp;end&nbsp; .-> __end__;
	select_next_draft -.-> collect_review_decision;
	transcribe_recording --> diarize_speakers;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
